server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 1234
    username: user
    url: jdbc:postgresql://localhost:5432/registration
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql:true
    show-sql: true
